const RAW_UNIVERSITIES = [
  // Top Central & Technological Institutes (IITs, NITs, IIITs, IISc, AIIMS, IIMs)
  'Indian Institute of Technology (IIT) Bombay',
  'Indian Institute of Technology (IIT) Delhi',
  'Indian Institute of Technology (IIT) Madras',
  'Indian Institute of Technology (IIT) Ropar',
  'Indian Institute of Technology (IIT) Kanpur',
  'Indian Institute of Technology (IIT) Kharagpur',
  'Indian Institute of Technology (IIT) Roorkee',
  'Indian Institute of Technology (IIT) Guwahati',
  'Indian Institute of Technology (IIT) BHU Varanasi',
  'Indian Institute of Technology (IIT) Hyderabad',
  'Indian Institute of Technology (IIT) Gandhinagar',
  'Indian Institute of Technology (IIT) Indore',
  'Indian Institute of Technology (IIT) Jodhpur',
  'Indian Institute of Technology (IIT) Mandi',
  'Indian Institute of Technology (IIT) Patna',
  'Indian Institute of Technology (IIT) Bhubaneswar',
  'Indian Institute of Technology (IIT) Tirupati',
  'Indian Institute of Technology (IIT) Palakkad',
  'Indian Institute of Technology (IIT) Goa',
  'Indian Institute of Technology (IIT) Jammu',
  'Indian Institute of Technology (IIT) Dharwad',
  'Indian Institute of Technology (IIT) Bhilai',

  // NITs & IIITs
  'National Institute of Technology (NIT) Trichy',
  'National Institute of Technology (NIT) Surathkal',
  'National Institute of Technology (NIT) Rourkela',
  'National Institute of Technology (NIT) Warangal',
  'National Institute of Technology (NIT) Calicut',
  'National Institute of Technology (NIT) Kurukshetra',
  'Dr B R Ambedkar National Institute of Technology (NIT) Jalandhar',
  'National Institute of Technology (NIT) Durgapur',
  'National Institute of Technology (NIT) Silchar',
  'Malaviya National Institute of Technology (MNIT) Jaipur',
  'Motilal Nehru National Institute of Technology (MNNIT) Allahabad',
  'Maulana Azad National Institute of Technology (MANIT) Bhopal',
  'Visvesvaraya National Institute of Technology (VNIT) Nagpur',
  'Sardar Vallabhbhai National Institute of Technology (SVNIT) Surat',
  'International Institute of Information Technology (IIIT) Hyderabad',
  'International Institute of Information Technology (IIIT) Bangalore',
  'Indraprastha Institute of Information Technology (IIIT) Delhi',
  'Indian Institute of Information Technology (IIIT) Allahabad',
  'Indian Institute of Information Technology (IIIT) Lucknow',
  'ABV-IIITM Gwalior',

  // Region 1: Punjab, Chandigarh, Himachal & Jammu
  'Chitkara University, Punjab',
  'Chitkara University, Himachal Pradesh',
  'Chandigarh University, Mohali',
  'PEC Punjab Engineering College, Chandigarh',
  'Thapar Institute of Engineering & Technology, Patiala',
  'Panjab University (PU), Chandigarh',
  'Lovely Professional University (LPU), Phagwara',
  'Indian Institute of Science Education and Research (IISER), Mohali',
  'Guru Nanak Dev University (GNDU), Amritsar',
  'Punjabi University, Patiala',
  'I K Gujral Punjab Technical University (PTU), Jalandhar',
  'Chandigarh Group of Colleges (CGC), Landran',
  'Chandigarh Group of Colleges (CGC), Jhanjeri',
  'Himachal Pradesh University (HPU), Shimla',
  'Himachal Pradesh Technical University (HPTU), Hamirpur',
  'Jaypee University of Information Technology (JUIT), Waknaghat',
  'Shoolini University, Solan',
  'University of Jammu, Jammu',
  'University of Kashmir, Srinagar',

  // Region 2: Haryana, Delhi NCR & Uttar Pradesh
  'Ashoka University, Sonepat',
  'O.P. Jindal Global University, Sonepat',
  'Kurukshetra University, Kurukshetra',
  'Maharshi Dayanand University (MDU), Rohtak',
  'JC Bose University of Science & Technology (YMCA), Faridabad',
  'Gurugram University, Gurugram',
  'University of Delhi (DU), New Delhi',
  'Jawaharlal Nehru University (JNU), New Delhi',
  'Jamia Millia Islamia (JMI), New Delhi',
  'Guru Gobind Singh Indraprastha University (GGSIPU), Delhi',
  'Delhi Technological University (DTU), Delhi',
  'Netaji Subhas University of Technology (NSUT), Delhi',
  'Banaras Hindu University (BHU), Varanasi',
  'Aligarh Muslim University (AMU), Aligarh',
  'Dr. A.P.J. Abdul Kalam Technical University (AKTU), Lucknow',
  'Amity University, Noida',
  'Amity University, Gurgaon',
  'Amity University, Lucknow',
  'Shiv Nadar University, Greater Noida',
  'Bennett University, Greater Noida',
  'Jaypee Institute of Information Technology (JIIT), Noida',
  'Harcourt Butler Technical University (HBTU), Kanpur',
  'Madan Mohan Malaviya University of Technology (MMMUT), Gorakhpur',
  'GL Bajaj Institute of Technology & Management, Greater Noida',
  'KIET Group of Institutions, Ghaziabad',

  // Region 3: Rajasthan, MP & Gujarat
  'BITS Pilani, Rajasthan',
  'Rajasthan Technical University (RTU), Kota',
  'LNM Institute of Information Technology (LNMIIT), Jaipur',
  'Manipal University, Jaipur',
  'Jaipur National University, Jaipur',
  'Savitribai Phule University / DAVV, Indore',
  'Maulana Azad National Institute of Technology, Bhopal',
  'Gujarat Technological University (GTU), Ahmedabad',
  'Dhirubhai Ambani Institute (DA-IICT), Gandhinagar',
  'Nirma University, Ahmedabad',
  'Pandit Deendayal Energy University (PDEU), Gandhinagar',

  // Region 4: Maharashtra, Goa & South India
  'University of Mumbai, Mumbai',
  'Savitribai Phule Pune University (SPPU), Pune',
  'Veermata Jijabai Technological Institute (VJTI), Mumbai',
  'College of Engineering Pune (COEP), Pune',
  'NMIMS University, Mumbai',
  'Symbiosis International University, Pune',
  'BITS Pilani, Goa Campus',
  'Indian Institute of Science (IISc), Bangalore',
  'Visvesvaraya Technological University (VTU), Belagavi',
  'Manipal Academy of Higher Education (MAHE), Manipal',
  'Christ University, Bangalore',
  'PES University, Bangalore',
  'MS Ramaiah Institute of Technology, Bangalore',
  'BMS College of Engineering, Bangalore',
  'RV College of Engineering (RVCE), Bangalore',
  'Anna University, Chennai',
  'Vellore Institute of Technology (VIT), Vellore',
  'Vellore Institute of Technology (VIT), Chennai',
  'Vellore Institute of Technology (VIT), Andhra Pradesh',
  'Vellore Institute of Technology (VIT), Bhopal',
  'SRM Institute of Science and Technology, Chennai',
  'SSN College of Engineering, Chennai',
  'BITS Pilani, Hyderabad Campus',
  'JNTU Hyderabad, Telangana',
  'Osmania University, Hyderabad',
  'KL University, Guntur',
  'APJ Abdul Kalam Technological University (KTU), Kerala',

  // Region 5: East & North-East India
  'Jadavpur University, Kolkata',
  'MAKAUT, West Bengal',
  'Calcutta University, Kolkata',
  'IIEST Shibpur, West Bengal',
  'Siksha \'O\' Anusandhan (SOA), Bhubaneswar',
  'KIIT University, Bhubaneswar',
  'Tezpur University, Assam',
  'Gauhati University, Guwahati',
  'North-Eastern Hill University (NEHU), Shillong'
];

export const INDIAN_UNIVERSITIES = Array.from(new Set(RAW_UNIVERSITIES)).sort((a, b) => a.localeCompare(b));
